ruta1:
  origen: "EL QUE SEA"
  destino: "kafka:{{kafka.topic.personas}}"

camel:
  springboot:
    main-run-controller: true # Esto le indica a Spring que debe mantener la app en ejecución... 
                              # que camel tiene configuradas rutas,... que se quedan corriendo como un servicio