ruta1:
  origen: "jpa:com.curso.camel.model.PersonaInImpl?consumeDelete=true&delay=5000&initialDelay=1000&consumeLockEntity=false&maximumResults=100"
  destino: "log:destino1?showAll=true&multiline=true"
  destino2: "log:destino2?showAll=true&multiline=true"

camel:
  springboot:
    main-run-controller: true # Esto le indica a Spring que debe mantener la app en ejecución... 
                              # que camel tiene configuradas rutas,... que se quedan corriendo como un servicio

# Datos de conexión a la BBDD
spring:
  datasource: # Ahora mariadb
    url:                jdbc:mariadb://18.202.220.100:3307/db #jdbc:h2:mem:personasdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE #jdbc:mariadb://18.202.220.100:3307/db
    driver-class-name:  org.mariadb.jdbc.Driver #org.h2.Driver
                        
    username:           usuario #sa
                        
    password:           password # (vacío)
  jpa:
    hibernate:
      ddl-auto: update # update, create, create-drop, validate, none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect:  org.hibernate.dialect.MariaDBDialect #org.hibernate.dialect.H2Dialect
                  
  sql:
    init:
      mode: always
      #platform: h2
      #schema-locations: classpath:/db/h2/schema-h2.sql
      #data-locations: classpath:/db/h2/data-h2.sql