DROP TABLE IF EXISTS personas_ivan;
  --# Versión H2 id bigint generated by default as identity,
  -- mariadb
  create table personas_ivan (
        id bigint auto_increment,
        dni varchar(255) not null,
        cp varchar(255) not null,
        direccion varchar(255) not null,
        email varchar(255) not null,
        fecha_de_nacimiento date not null,
        nombre varchar(255) not null,
        pais varchar(255) not null,
        poblacion varchar(255) not null,
        telefono varchar(255) not null,
        primary key (id)
    );


-- Datos de prueba para la tabla personas_ivan
INSERT INTO personas_ivan (dni, nombre, fecha_de_nacimiento, direccion, poblacion, cp, pais, telefono, email) 
VALUES ('230000T', 'Juan García Pérez', '1990-05-15', 'Calle Mayor 123', 'Madrid', '28001', 'España', '+34912345678', 'juan.garcia@example.com');

-- DNIs válidos (múltiplos de 23 terminados en T)
INSERT INTO personas_ivan (dni, nombre, fecha_de_nacimiento, direccion, poblacion, cp, pais, telefono, email) 
VALUES ('00000023T', 'María López Sánchez', '1985-03-20', 'Av. Libertad 45', 'Barcelona', '08001', 'España', '+34934567890', 'maria.lopez@example.com');

INSERT INTO personas_ivan (dni, nombre, fecha_de_nacimiento, direccion, poblacion, cp, pais, telefono, email) 
VALUES ('00000046T', 'Pedro Martínez Ruiz', '1992-07-12', 'Plaza España 8', 'Valencia', '46001', 'España', '+34961234567', 'pedro.martinez@example.com');

INSERT INTO personas_ivan (dni, nombre, fecha_de_nacimiento, direccion, poblacion, cp, pais, telefono, email) 
VALUES ('00000069T', 'Ana Fernández Torres', '1988-11-30', 'Calle Sol 67', 'Sevilla', '41001', 'España', '+34954123456', 'ana.fernandez@example.com');

INSERT INTO personas_ivan (dni, nombre, fecha_de_nacimiento, direccion, poblacion, cp, pais, telefono, email) 
VALUES ('00000092T', 'Carlos Rodríguez Díaz', '1995-02-14', 'Paseo Gracia 234', 'Barcelona', '08008', 'España', '+34932345678', 'carlos.rodriguez@example.com');

INSERT INTO personas_ivan (dni, nombre, fecha_de_nacimiento, direccion, poblacion, cp, pais, telefono, email) 
VALUES ('00000115T', 'Laura Gómez Moreno', '1991-09-05', 'Calle Luna 12', 'Málaga', '29001', 'España', '+34952345678', 'laura.gomez@example.com');

INSERT INTO personas_ivan (dni, nombre, fecha_de_nacimiento, direccion, poblacion, cp, pais, telefono, email) 
VALUES ('00000138T', 'Jorge Sánchez Jiménez', '1987-12-18', 'Av. Constitución 89', 'Zaragoza', '50001', 'España', '+34976234567', 'jorge.sanchez@example.com');

INSERT INTO personas_ivan (dni, nombre, fecha_de_nacimiento, direccion, poblacion, cp, pais, telefono, email) 
VALUES ('00000161T', 'Isabel Hernández Gil', '1993-04-22', 'Calle Real 56', 'Bilbao', '48001', 'España', '+34944567890', 'isabel.hernandez@example.com');

INSERT INTO personas_ivan (dni, nombre, fecha_de_nacimiento, direccion, poblacion, cp, pais, telefono, email) 
VALUES ('00000184T', 'Miguel Álvarez Ramos', '1989-08-07', 'Plaza Mayor 3', 'Valladolid', '47001', 'España', '+34983345678', 'miguel.alvarez@example.com');

-- DNIs inválidos (no cumplen el algoritmo)
INSERT INTO personas_ivan (dni, nombre, fecha_de_nacimiento, direccion, poblacion, cp, pais, telefono, email) 
VALUES ('12345678Z', 'Lucía Pérez Navarro', '1994-01-15', 'Calle Norte 78', 'Madrid', '28002', 'España', '+34915678901', 'lucia.perez@example.com');

INSERT INTO personas_ivan (dni, nombre, fecha_de_nacimiento, direccion, poblacion, cp, pais, telefono, email) 
VALUES ('23456789B', 'Antonio Ruiz Castro', '1986-06-25', 'Av. Sur 45', 'Granada', '18001', 'España', '+34958234567', 'antonio.ruiz@example.com');

INSERT INTO personas_ivan (dni, nombre, fecha_de_nacimiento, direccion, poblacion, cp, pais, telefono, email) 
VALUES ('34567890C', 'Carmen Díaz Morales', '1990-10-30', 'Calle Este 23', 'Murcia', '30001', 'España', '+34968345678', 'carmen.diaz@example.com');

INSERT INTO personas_ivan (dni, nombre, fecha_de_nacimiento, direccion, poblacion, cp, pais, telefono, email) 
VALUES ('45678901D', 'Francisco Moreno Ortiz', '1992-03-08', 'Plaza Oeste 67', 'Alicante', '03001', 'España', '+34965456789', 'francisco.moreno@example.com');

INSERT INTO personas_ivan (dni, nombre, fecha_de_nacimiento, direccion, poblacion, cp, pais, telefono, email) 
VALUES ('56789012E', 'Rosa Torres Vega', '1988-07-19', 'Calle Centro 90', 'Córdoba', '14001', 'España', '+34957567890', 'rosa.torres@example.com');

INSERT INTO personas_ivan (dni, nombre, fecha_de_nacimiento, direccion, poblacion, cp, pais, telefono, email) 
VALUES ('67890123F', 'Manuel Jiménez Serrano', '1991-11-11', 'Av. Principal 12', 'Santander', '39001', 'España', '+34942678901', 'manuel.jimenez@example.com');

INSERT INTO personas_ivan (dni, nombre, fecha_de_nacimiento, direccion, poblacion, cp, pais, telefono, email) 
VALUES ('78901234G', 'Elena Castro Fuentes', '1987-05-28', 'Calle Segunda 45', 'Pamplona', '31001', 'España', '+34948789012', 'elena.castro@example.com');

INSERT INTO personas_ivan (dni, nombre, fecha_de_nacimiento, direccion, poblacion, cp, pais, telefono, email) 
VALUES ('89012345H', 'David Ortiz Cabrera', '1993-09-16', 'Plaza Central 78', 'Oviedo', '33001', 'España', '+34985890123', 'david.ortiz@example.com');

INSERT INTO personas_ivan (dni, nombre, fecha_de_nacimiento, direccion, poblacion, cp, pais, telefono, email) 
VALUES ('90123456J', 'Beatriz Serrano Molina', '1989-12-03', 'Calle Tercera 34', 'Logroño', '26001', 'España', '+34941901234', 'beatriz.serrano@example.com');

INSERT INTO personas_ivan (dni, nombre, fecha_de_nacimiento, direccion, poblacion, cp, pais, telefono, email) 
VALUES ('11111111K', 'Raúl Vega Campos', '1995-02-20', 'Av. Diagonal 56', 'Toledo', '45001', 'España', '+34925111111', 'raul.vega@example.com');

INSERT INTO personas_ivan (dni, nombre, fecha_de_nacimiento, direccion, poblacion, cp, pais, telefono, email) 
VALUES ('22222222L', 'Sandra Molina Reyes', '1986-08-12', 'Calle Cuarta 89', 'Badajoz', '06001', 'España', '+34924222222', 'sandra.molina@example.com');

INSERT INTO personas_ivan (dni, nombre, fecha_de_nacimiento, direccion, poblacion, cp, pais, telefono, email) 
VALUES ('33333333M', 'Alberto Campos Prieto', '1990-04-07', 'Plaza Nueva 23', 'Cáceres', '10001', 'España', '+34927333333', 'alberto.campos@example.com');

INSERT INTO personas_ivan (dni, nombre, fecha_de_nacimiento, direccion, poblacion, cp, pais, telefono, email) 
VALUES ('44444444N', 'Patricia Reyes Blanco', '1992-10-25', 'Calle Quinta 67', 'Albacete', '02001', 'España', '+34967444444', 'patricia.reyes@example.com');